// Mocks generated by Mockito 5.4.4 from annotations
// in busfeed_driver/test/widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:busfeed_driver/models/user.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [User].
///
/// See the documentation for Mockito's code generation for more information.
class MockUser extends _i1.Mock implements _i2.User {
  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  String get appId => (super.noSuchMethod(
        Invocation.getter(#appId),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#appId),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.getter(#appId),
        ),
      ) as String);

  @override
  set userExpiryCallback(dynamic Function()? _userExpiryCallback) =>
      super.noSuchMethod(
        Invocation.setter(
          #userExpiryCallback,
          _userExpiryCallback,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get authenticated => (super.noSuchMethod(
        Invocation.getter(#authenticated),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  String get authorization => (super.noSuchMethod(
        Invocation.getter(#authorization),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#authorization),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.getter(#authorization),
        ),
      ) as String);

  @override
  set authorization(String? value) => super.noSuchMethod(
        Invocation.setter(
          #authorization,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get expired => (super.noSuchMethod(
        Invocation.getter(#expired),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set expired(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #expired,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get email => (super.noSuchMethod(
        Invocation.getter(#email),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#email),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.getter(#email),
        ),
      ) as String);
}
