name: Flutter Web
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.WEB_APP_DEPLOY}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with: 
          token: ${{secrets.WEB_APP_DEPLOY}}
      - uses: subosito/flutter-action@v2.12.0
        with:
          flutter-version: '3.16.8'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
      - run: |
          cd build/web
          git init
          git config --global user.email diarmuidr3d@gmail.com 
          git config --global user.name diarmuidr3d 
          git remote add origin https://diarmuidr3d:${{secrets.WEB_APP_DEPLOY}}:github.com/busfeedie/busfeed-driver.git
          git status
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
