name: test
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Run flutter tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: subosito/flutter-action@v2.12.0
        with:
          flutter-version: '3.16.8'
      - run: flutter test
